# coding: utf-8

# flake8: noqa
"""
    HurdleTrade_API

    HurdleTrade_API Test  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
